### ISSUE TITLE
[PE-D][Tester B] AnUdder details varies from  image shown in the User Guide

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-F08-3/tp#168]
![Screenshot 2024-11-08 at 4.18.07 PM.png](https://raw.githubusercontent.com/LinkesV/ped/main/files/8a811507-d974-408d-b75a-6373bf89fb33.png)

As can be seen from above, there is no uniformity in the spacing that is given and there are random spaces given between the : and the details of the person.

This contrasts with the image that is shown in the User Guide below:

![Screenshot 2024-11-08 at 5.10.45 PM.png](https://raw.githubusercontent.com/LinkesV/ped/main/files/d018c0ae-d7c1-44ad-98ec-e4749466578f.png)

Hence, I think the best modification for this is either to update the images in the User Guide such that they match your current application. (Or hopefully you can modify the UI to have uniform spacing)

-------------
Labels: `type.DocumentationBug` `severity.VeryLow`
original: LinkesV/ped#1

**Comment by XinghuaJulia** [comment]
add this to planned enhancement to accommodate for Mac styling issues
