### ISSUE TITLE
[PE-D][Tester E] Missing proposed feature in DG

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-F08-3/tp#175]
Missing explanation for proposed feature in DG  on page 10.
![image.png](https://raw.githubusercontent.com/verakohh/ped/main/files/eba7b2a3-3ec9-40f3-bbd4-673bc2d7bff9.png)

-------------
Labels: `severity.Low` `type.DocumentationBug`
original: verakohh/ped#11

**Comment by PeterHW963** [comment]
Tweak DG
