### ISSUE TITLE
[PE-D][Tester A] delete command does not update the top right panel in the gui even if the person is deleted. 

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-F08-3/tp#186]
When I entered `delete 2`, I deleted Bernice successfully, but her name still appeared in the top right panel of the gui.

It only changes the display if I I manually click on the contact in the contact list on the left

![image.png](https://raw.githubusercontent.com/ITZXITZX/ped/main/files/b5fbebf0-4530-4a3a-a89e-52dd5ceec6b2.png)

-------------
Labels: `type.FunctionalityBug` `severity.Low`
original: ITZXITZX/ped#6

**Comment by PeterHW963** [comment]
There must have been some steps that he missed that caused that bug. All 5 of us tried to reproduce this bug and it doesn't happen

**Comment by PeterHW963** [comment]
planned enhancement: more detailPanel corrections i.e. deleting until last person leaves detail still on detailpanel
