### ISSUE TITLE
[PE-D][Tester E] Missing numberings for use cases in DG

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-F08-3/tp#189]
![image.png](https://raw.githubusercontent.com/verakohh/ped/main/files/f15cf7ae-a387-4715-a99c-909c355326ef.png)

Missing numberings for use cases in DG 
For example, 'UC01', 'UC02'

-------------
Labels: `type.DocumentationBug` `severity.Medium`
original: verakohh/ped#14

**Comment by PeterHW963** [comment]
wrong severity, but yeah its a good pt
