### ISSUE TITLE
[PE-D][Tester B] Window when displaying meetings is too small

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-F08-3/tp#197]
Meetings lists is way too small not user friendly. I am unable to view the details of meetings properly since one single meeting barely fits in the window provided.

I think a good solution would be to allow resizing for the meetings or expand the window so I can view the details of all my meetings. Or use the window that displays details of the contact to change to show a list of meetings.

![Screenshot 2024-11-08 at 5.53.20 PM.png](https://raw.githubusercontent.com/LinkesV/ped/main/files/36ecf12a-9dde-43c7-a06c-3393de8fb038.png)

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: LinkesV/ped#9

**Comment by PeterHW963** [comment]
add to planned enhancement
