### ISSUE TITLE
[PE-D][Tester C] Violation of project constraints

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-F08-3/tp#207]
![image.png](https://raw.githubusercontent.com/isaactodo/ped/main/files/31c41431-9263-4d28-b0fa-a1ce1b563c5a.png)

This is a violation of **Constraint-No-Remote-Server**.  Hopefully, it will not be implemented.

-------------
Labels: `type.FeatureFlaw` `severity.VeryLow`
original: isaactodo/ped#15

**Comment by PeterHW963** [comment]
what the..... bro is high
