### ISSUE TITLE
Change the warning for editing JSON file to cover all cases

### ISSUE THREAD

**Issue by psh12320** [AY2425S1-CS2103T-F08-3/tp#228]
<img width="680" alt="image" src="https://github.com/user-attachments/assets/7a245f85-ba49-44bf-9b5f-b4f7a226d9cd">

We should also add in that they should not edit the JSON file **after using the application** either, add in any invalid entry, and then open it, which might lead to unexpected behaviour. I think Tester C did just that.

**Comment by XinghuaJulia** [comment]
Then might as well just say don't edit at all (e.g.)
Take note to never edit the JSON file.
